- assets/scss/_variables_project.scss
> Update primary doc color to Cobalt blue

- assets/scss/_variables_project.scss
> [DOCS-9] Update link color

- layouts/_default/sitemap.xml
> [DOCS-23] Set up sitemap.xml with full URL

- content/en/Getting started/_index.md
- content/en/Getting started/planning.md
* The "Overview" is the list of "basic" steps, to help readers visualize the process
* Also fixed a typo which led to a bad lik
* Refined some text
> [DOCS-43] Add an Overview Title to the opening page

- content/en/Getting started/Assets/_index.md
- content/en/Getting started/Assets/asset-description.md
- content/en/Getting started/Assets/coverage.md
- content/en/Getting started/What to Expect/_index.md
- content/en/Getting started/checklist.md
- content/en/Getting started/sign-in.md
- layouts/shortcodes/pentest-report-requirements.html
Based on input from richard.jones@cobalt.io
Richard, I'm not addressing all of your feedback, as this is a "Getting Started" guide. I'll list what I didn't address in the (internal to Cobalt) Jira.
> [DOCS-58] Address feedback on Getting Started guide

- content/en/Getting started/_index.md
- content/en/Getting started/checklist.md
- content/en/Getting started/planning.md
- content/en/_index.md
- styles/Google/Exclamation.yml
- styles/write-good/Weasel.yml
Approved by Eleanna Smpokou via Cobalt internal discussion (I[nternal-only link](https://zombie.atlassian.net/wiki/spaces/PRODUCT/pages/2307916076/User+Interview+with+Don+from+Brown+Toland?focusedCommentId=2325381512#comment-2325381512))
> [DOCS-64] Customer feedback. Minimize marketing-type content.

- config.toml
- content/en/Getting started/Assets/_index.md
- jobdesc.md
* Include an "Edit this page" link on every page
* Link opens the page in GitHub, with the ability to create a PR
* Based on https://www.docsy.dev/docs/adding-content/repository-links/
> [DOCS-79] Include links to modify pages via GitHub

- content/en/Getting started/What to Expect/_index.md
Clarify what we won't do to customize a pentest report.
> [DOCS-81] Update info on customizing reports: tiers, reporting all findings

- content/en/Getting started/Pentest objectives/test-credentials.md
> [DOCS-92] Update test credential text

- content/en/Getting started/What to Expect/report-contents.md
- content/en/Getting started/details.md
- content/en/Getting started/glossary.md
- layouts/shortcodes/environment.md
- layouts/shortcodes/pentest-report-types.md
- layouts/shortcodes/ptaas-tier.md
I've created this PR as a foundation for other (internal) issues where we should describe how users can "customize" pentest reports.
In any case, you can review the build of my changes here: https://deploy-preview-104--cobalt-docs.netlify.app/getting-started/what-to-expect/report-contents/
> [DOCS-95] Add general details for each section of a pentest report

- LICENSE
Awaiting approval from legal.
Once approved, I'll remove the do-not-merge label, and merge.
> [DOCS-59] Add CC BY 4.0 license

- content/en/Getting started/What to Expect/_index.md
- content/en/Getting started/glossary.md
- content/en/Getting started/planning.md
Fixed minor typos and punctuation errors in four files.
> Fix typos and punctuation in GSG

- content/en/Getting started/Pentest objectives/Methodologies/api-methodologies.md
- content/en/Getting started/Pentest objectives/Methodologies/cloud.md
- content/en/Getting started/Pentest objectives/Methodologies/external-network.md
- content/en/Getting started/Pentest objectives/Methodologies/internal-network.md
- content/en/Getting started/Pentest objectives/Methodologies/mobile.md
- content/en/Getting started/Pentest objectives/Methodologies/web-methodologies.md
- content/en/Getting started/What to Expect/_index.md
- layouts/shortcodes/min-credits-report.md
- Set up a shortcode, so we call the same content in all required locations
- Facilitate changes to credit definitions
> [DOCS-138] Standarize Min credits for pentest report

- config.toml
- layouts/_default/baseof.html
- layouts/partials/analytics-gtag.html
- layouts/partials/head.html
@mjang Please feel free to reject. It's totally a "I-will-still-try-it-even-if-not-sure" approach.
Breaking the portal is the last thing I want to do.
> [DOCS-153] Add GA4 Tracking Code to subdomain

- content/en/Getting started/Sign In/_index.md
- content/en/Getting started/Sign In/account-recovery.md
- layouts/shortcodes/sign-in.md
@molfinn Please review the updates describing the account recovery process.
This is how the changes will appear on the portal:
https://deploy-preview-138--cobalt-docs.netlify.app/getting-started/sign-in/account-recovery/
> [DOCS-151] Account Recovery 

- content/en/Getting started/checklist.md
- content/en/Getting started/glossary.md
@yogipetkar Please review the updates describing co-branded pentest reports.
> [DOCS-160] Co-branded Pentest Reports

- content/en/Getting started/Assets/_index.md
- content/en/Getting started/Assets/asset-type.md
- content/en/Getting started/Pentest objectives/pentest-target.md
- content/en/Getting started/Sign In/_index.md
- content/en/Getting started/What to Expect/report-contents.md
- content/en/Getting started/customize-report.md
- content/en/Getting started/details.md
- content/en/Getting started/planning.md
- layouts/shortcodes/big-pic-UI-steps.md
- layouts/shortcodes/ptaas-tier.md
A bunch of minor updates to Product Docs.
> [DOCS-152] Minor Updates to Product Docs

- content/en/Getting started/Sign In/_index.md
- content/en/Getting started/Sign In/account-recovery.md
- content/en/Getting started/glossary.md
@molfinn Please review the updates describing changes to SAML SSO.
This is how the changes will appear on the portal: https://deploy-preview-140--cobalt-docs.netlify.app/getting-started/sign-in/
`Learn more about [configuring SAML SSO](https://cobaltio.zendesk.com/hc/en-us/sections/360012774052--SAML-SSO-).` The link here will be changed as soon as we finalize [DOCS-157](https://zombie.atlassian.net/browse/DOCS-157).
> [DOCS-142] SAML SSO for All Tiers

- content/en/Getting started/Pentest objectives/Methodologies/web-methodologies.md
- styles/Spelling.yml
- styles/cobalt/spelling-exceptions.txt
- Include more complete info
- Set up progressive disclosure for complete info with expand functionality
@ana-dashuk-cobalt While I'd like your approval, I'm going to wait until we get Marion's review before merging (and proceeding with the other parts of the Jira.
Also, this helps me assess the workload required to convert the 67? Zendesk articles that we want to convert to product docs
> [DOCS-164] Update Web methodologies page

- content/en/BestPractices/style_suggestions.md
Thanks to Jake Fox for finding these errors
> [NO-TICKET] Fix links in (hidden) style file

- content/en/Getting started/glossary.md
@molfinn Minor update for the visibility of email addresses.
> [DOCS-214] People > Organization: Admins can view emails addresses

- content/en/BestPractices/prevent-security-misconfig.md
Hi @shadixit,
Thank you for your pull request, https://github.com/cobalthq/cobalt-product-public-docs/pull/151
I've tried a rewrite of your content, and set it up in this PR. When I rewrote your content, I tried to:
- Keep your messaging
- Improve readability
- Remove duplications
- Focus on [Active Voice](https://developers.google.com/style/voice)
Please let me know if there are any mistakes.
Can you please also specify the language used in the code samples so that we could highlight the syntax properly?
This is how the PR will appear in our Product Docs: https://deploy-preview-157--cobalt-docs.netlify.app/bestpractices/prevent-security-misconfig/
(Note: I can't make you a "Reviewer" as we have limits on our GitHub subscription. However, you should still be able to review each line of …
> [DOCS-231] Best Practices: Prevent Security Misconfiguration

- content/en/BestPractices/template.md
@ana-dashuk-cobalt FYI. Otherwise we get
> [NO Ticket] Fix bad link name

- content/en/BestPractices/_index.md
- content/en/BestPractices/prevent-security-misconfig.md
- content/en/BestPractices/protect-against-ssrf.md
- layouts/shortcodes/shashank.md
Per Shashank's request. 
I don't know why, but changing the order in the table fixed the formatting problem you ID'd earlier today (at least in the local build.)
> [DOCS-230] Update shashank's link

- content/en/Getting started/Assets/asset-description.md
- content/en/Getting started/what-to-expect.md
- layouts/shortcodes/contact-csm-support.md
@mjang I'm setting up this no-ticket PR to add a new shortcode as per your suggestion in https://github.com/cobalthq/cobalt-product-public-docs/pull/171
> [NO-TICKET] New shortcode: contact CSM or support

- content/en/Getting started/what-to-expect.md
- content/en/Platform Deep Dive/Pentests/Reports/report-contents.md
Jira Ticket: [FOUND-562](https://zombie.atlassian.net/browse/FOUND-562)
Renaming Re-Test to Retest
Related PRs:
https://github.com/cobalthq/cobalt-app-web/pull/3839
https://github.com/cobalthq/cobalt-pentest-api/pull/3240
https://github.com/cobalthq/cobalt-admin-api/pull/1007
> [FOUND-562] rename Re-Test to Retest

- config.toml
- content/search.md
- layouts/partials/body-end.html
- layouts/partials/head-end.html
> [NO TICKET] Test PR for search feature

- config.toml
- content/search.md
- layouts/partials/body-end.html
- layouts/partials/head-end.html
Reverts cobalthq/cobalt-product-public-docs#175
> Revert "[NO TICKET] Test PR for search feature"

- package-lock.json
> [CIP-1885] Update npm packages

- layouts/partials/section-index.html
Reverts cobalthq/cobalt-product-public-docs#205
> Revert "[DOCS-309] Manual Links (Links in Section Names)"

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
Note: with htmltest, I found an Alt Text issue with the images in the `Integrations/_index.md` file. We'll address that separately. The question for you, @ana-dashuk-cobalt , is whether these instructions work for you.
n/a
| [README section on htmltest] | [Test Links and Alt Attributes](https://github.com/cobalthq/cobalt-product-public-docs/pull/222/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L75) | [Procedure to install the htmltest tool] |
To see how this change looks in production, see the link to the README in the PR, starting with line 75
n/a
> [NO-TICKET] Update link tester instructions

- content/en/Platform Deep Dive/Pentests/Pentest Process/Methodologies/web-methodologies.md
Note: this establishes the "pattern" that I plan to follow in related Jiras for other pentest methodologies.
@ana-dashuk-cobalt FYI, I'm discussing this change with the CSM, separately by DM.
| [Web Methodologies](https://developer.cobalt.io/platform-deep-dive/pentests/pentest-process/methodologies/web-methodologies/) | [Update](https://deploy-preview-226--cobalt-docs.netlify.app/platform-deep-dive/pentests/pentest-process/methodologies/web-methodologies/) | [Changes as requested by CSM] |
Help us support a “Write once, publish everywhere” single source of truth. …
> [DOCS-285] Update Web methodologies page with detail

- content/en/APIUseCases/create_asset.md
- content/en/Getting started/what-to-expect.md
- content/en/Platform Deep Dive/Pentests/Findings/remediate-findings.md
| Pentest Expectations | https://deploy-preview-262--cobalt-docs.netlify.app/getting-started/what-to-expect/  | Since now we have a section about findings, I added cross-references to support SSoT | …
> [NO-TICKET] Update Pentest Expectations

- content/en/Product Updates/_index.md
| Product Updates | https://deploy-preview-243--cobalt-docs.netlify.app/product-updates/ | New book with cross-references to the release blog |
If we accept this change, let's wait until the second entry for December is published.
We can change the page layout. I experimented with tables, lists, and H3 headings. …
> [DOCS-345] New Product Updates Book

- content/en/Platform Deep Dive/Pentests/Findings/remediate-findings.md
| Free Retesting Duration | https://deploy-preview-290--cobalt-docs.netlify.app/platform-deep-dive/pentests/findings/remediate-findings/#free-retesting-duration | Added time `23:59 UTC` | …
> [NO-TICKET] Free Retesting Duration Time

- config.toml
[Deploy preview](https://deploy-preview-304--cobalt-docs.netlify.app/)
| Before | After |
| ----- | ----- |
| ![Screenshot 2023-03-01 at 12 19 17](https://user-images.githubusercontent.com/106706890/222124954-58b8e6ce-bdfe-4586-a200-b906876d5433.png) | ![Screenshot 2023-03-01 at 12 20 07](https://user-images.githubusercontent.com/106706890/222125138-9a2a4610-63b4-4cc5-b583-9a08f3151097.png) |
You’ve found a [shortcode](https://gohugo.io/content-management/shortcodes/) that we include in …
> [NO-TICKET] Update the navigation menu

- content/en/Platform Deep Dive/Collaboration/Organization/Organization Settings/saml-sso.md
| Configuration Instructions for Specific Identity Providers | [Link](https://deploy-preview-330--cobalt-docs.netlify.app/platform-deep-dive/collaboration/organization/organization-settings/saml-sso/#configuration-instructions-for-specific-identity-providers) | Added instructions for specific IdPs |
You’ll find the …
> [DOCS-157] Configuration Instructions (SAML SSO)

- content/en/Getting started/planning.md
- content/en/Platform Deep Dive/Pentests/pentest-types.md
- layouts/shortcodes/agile-credits.md
- layouts/shortcodes/comprehensive-credits.md
| Plan and Scope the Pentest, Pentest Types |  | Removed references to credit minimums |
That shortcode has the same base name as what you see in the PR, such as …
> [NO-TICKET] Credit minimums

- content/en/Integrations/Beta/_index.md
- content/en/Integrations/_index.md
- layouts/shortcodes/beta-integrations-list.md
Added a shortcode for beta integrations.
Be sure to check for broken links and …
> [NO-TICKET] Minor update

- content/en/BestPractices/secure-design.md
- content/en/Getting started/_index.md
| Getting Started | [Link](https://deploy-preview-355--cobalt-docs.netlify.app/getting-started/#prepare-for-a-pentest) | |
That shortcode has the same base name as …
> [NO-TICKET] Prepare for a pentest

- content/en/Methodologies/_index.md
- content/en/Methodologies/azure-ad.md
| Azure AD Penetration Testing Methodologies | [Link](https://deploy-preview-363--cobalt-docs.netlify.app/methodologies/azure-ad/) | |
That shortcode has the same …
> [DOCS-455] Azure AD Pentest Methodologies

- content/en/BestPractices/_index.md
- content/en/Cobalt-API/create_asset.md
- content/en/Cobalt-API/get-findings.md
- content/en/Getting started/pentest-preparation.md
- content/en/Integrations/Beta/configure-beta.md
- content/en/Integrations/Jira/jira-cloud.md
- content/en/Integrations/Jira/jira-server-dc.md
- content/en/Integrations/Jira/push-findings.md
- content/en/Integrations/Jira/troubleshoot-jira-integration.md
- content/en/Integrations/defectdojo.md
- content/en/Integrations/github.md
- content/en/Integrations/kenna-security.md
- content/en/Integrations/webhooks.md
- content/en/Platform Deep Dive/Organization/Organization Settings/SAML SSO/_index.md
- content/en/Professional Services/_index.md
Updated some links, other minor updates.
Be sure to check for broken links and …
> [NO-TICKET] Minor updates

- content/en/BestPractices/api-rate-limiting.md
> Update link on api-rate-limiting.md

- content/en/Getting started/sign-in.md
- content/en/Platform Deep Dive/Cobalt Account/account-recovery.md
- layouts/shortcodes/sign-in.md
> [FND-2430] Change verify it's you to verify your browser

- content/en/Platform Deep Dive/Domains/_index.md
Addressing feedback from slack that domains is difficult to read
> Add bullets within Domain docs

- content/en/Cobalt-API/v1/_index.md
- content/en/Cobalt-API/v2/_index.md
Add embeds for the public API documentation to the product documentation hub.
Supersedes #416
> [FND-3175] Public API documentation embed

- netlify.toml
Based on <https://docs.netlify.com/configure-builds/file-based-configuration/#redirects>
See also #432
> [FND-3175] Set `force = true` for domain redirects

- netlify.toml
Based on <https://docs.netlify.com/routing/redirects/redirect-options/#splats>
See also #434
> [FND-3175] Redirect subpaths as well

- content/en/Platform Deep Dive/Scans/_index.md
https://zombie.atlassian.net/browse/ST-224
| Scans | https://deploy-preview-446--cobalt-docs.netlify.app/platform-deep-dive/scans/ | |
That shortcode has the same …
> Update scans product info

- content/en/Getting started/glossary.md
> Update glossary specialized pentest

- content/en/Cybersecurity Services/_index.md
> Rename Cybersecurity Services 

- content/en/Cybersecurity Services/_index.md
- content/en/Platform Deep Dive/Credits/ptaas-tiers.md
> Update pro serve email alias to cybersecurity services

- content/en/Getting started/planning.md
- content/en/Methodologies/_index.md
- content/en/Methodologies/cloud.md
- content/en/Methodologies/desktop.md
> Fixing catogories typo in methodologies

- content/en/Methodologies/cloud.md
- content/en/Methodologies/desktop.md
- content/en/Methodologies/external-network.md
- content/en/Methodologies/internal-network.md
- content/en/Methodologies/mobile.md
> Update weight (order) of Methodologies in nav for mobile

- content/en/Integrations/Jira/troubleshoot-jira-integration.md
* Cobalt ingress IP addresses in Jira DC troubleshooting guide
Be sure to …
> [FND-3623] Document Cobalt ingress IP addresses in Jira DC troubleshooting guide

- content/en/Platform Deep Dive/Scans/_index.md
Scans -> DAST Scanner
https://deploy-preview-468--cobalt-docs.netlify.app/platform-deep-dive/scans/
[ ] Did you check for …
> Rename Scans to DAST Scanner

- content/en/Cybersecurity Services/_index.md
- content/en/Cybersecurity Services/digital-risk-assessment.md
- updated CSS page to include DRA & Engagements
- added new DRA child page  …
> Update Cybersecurity services section to include DRA

- content/en/Platform Deep Dive/Scans/_index.md
Be sure to check for broken links and Alt Text issues. We have a partially …
> Embed DAST video

- layouts/shortcodes/internal-network-system-req.md
> Update internal-network-system-req to 50 GB vs 20

- content/en/Platform Deep Dive/Scans/_index.md
- content/en/Platform Deep Dive/Scans/best-practices.md
- content/en/Platform Deep Dive/Scans/integrations.md
- content/en/Platform Deep Dive/Scans/targets.md
Ticket: https://zombie.atlassian.net/browse/FX-4650
I tried to add tips to avoid the common problems. I took some points from a [previous list composed by Nady](https://cobalthq.slack.com/archives/C057Z6JUVT4/p1718210134102939). Any other tips are welcome.
| Best practices | https://deploy-preview-527--cobalt-docs.netlify.app/platform-deep-dive/scans/best-practices/ |  |
| Configuring a target | https://deploy-preview-527--cobalt-docs.netlify.app/platform-deep-dive/scans/targets/#configuring-a-target |  |
To see how this change looks in production, scroll down to **Deploy Preview**. Select the link that looks like …
> DAST best practices

- content/en/Platform Deep Dive/Scans/_index.md
> Add details about geo-blocking

- content/en/Platform Deep Dive/Scans/faq.md
| DAST Scanner best practices | [Link](https://deploy-preview-537--cobalt-docs.netlify.app/platform-deep-dive/scans/faq/#we-use-an-external-service-for-form-based-authentication-can-the-dast-scanner-handle-this) |  | …
> Add a DAST Scanner login note

- content/en/Getting started/pentest-preparation.md
- content/en/Methodologies/internal-network.md
- layouts/shortcodes/internal-network-requirements.md
- layouts/shortcodes/osstmm-methodology.md
- layouts/shortcodes/report-triage-retest.md
> Chore/ss2 854/docs update internal network methodology

- content/en/Methodologies/ai-llm.md
> Ss2 896 product docs ai llm methodology update

- content/en/Methodologies/_index.md
- content/en/Methodologies/web-api-test-type.md
- content/en/Methodologies/web-methodologies.md
- layouts/shortcodes/report-triage-retest.md
> Chore/dl 179/update web methodology docs

- content/en/Getting started/details.md
- content/en/Getting started/testing-environments.md
> Chore/no tic/testing environments

- .github/dependabot.yml
- package-lock.json
- package.json
> [CO-199] Apply dependabot common config.

- content/en/Platform Deep Dive/Assets/_index.md
- content/en/Platform Deep Dive/Assets/insights.md
- content/en/Platform Deep Dive/Insights/_index.md
- content/en/Platform Deep Dive/Organization/Organization Settings/_index.md
> Chore/dl 386/org insights product documentation updates
