.gitignore, .htmltest.yml, README.md, content/en/Getting started/Pentest objectives/pentest-target.md
As described in DOCS-26
Netlify link checker does not work
htmltest almost works
Unable to install html-proofer due to Ruby installation isuses
Review another day. Include "howto" for `htmltest` in the README.
=> [DOCS-26] Test Netlify link checker plugin, checklinks

content/en/Getting started/_index.md, layouts/shortcodes/expand.html
This turned out better than I expected. @dannyleong39 I'd love your opinion/approval of this. I'm going to share with Stef as well before merging.
I think this can be an excellent tool to minimize any "walls of text" in our docs, based on Marketing feedback.
You can review the build here: https://deploy-preview-100--cobalt-docs.netlify.app/getting-started/
=> [DOCS-50] Testing 'Expand' code

content/en/Getting started/Assets/coverage.md, content/en/Getting started/What to Expect/_index.md, layouts/shortcodes/pentest-report-requirements.html
This should work for now, but I'll need to update with DOCS-94 for when we roll out our new credit definitions.
TLDR: to see the changes as built, see:
- https://deploy-preview-102--cobalt-docs.netlify.app/getting-started/assets/coverage/#pentest-reports
- https://deploy-preview-102--cobalt-docs.netlify.app/getting-started/checklist/#reports
The content of these pages both pull from [this file](https://github.com/cobalthq/cobalt-product-public-docs/blob/DOCS-93_support_automated_pentest_message/layouts/shortcodes/pentest-report-requirements.html)
Once merged, I'll propose a message (in the internal issue, DOCS-93)
=> [DOCS-93] Update when we support pentest reports

layouts/docs/list.html, layouts/partials/feedback.html, layouts/partials/taxonomy_terms_article.html, layouts/partials/taxonomy_terms_article_wrapper.html
In several docs pages, we have two sets of links to other pages, which IMO is confusing and poor UX. @yogipetkar I think this change helps minimize the distraction that you suggested in your (internal) Slack comment, as shown in the (internal) issue, DOCS-97.
cc @dannyleong39 as I think this promotes a "better UX"
As you can see from the build of this PR, I've now removed the links at the bottom of the page. I still need to set up more separation between our text and the feedback options -- so I'm moving this PR to "draft"
=> [DOCS-97] Remove bottom list menu for clarity

layouts/shortcodes/ptaas-tier.md
Yogi, since you removed the functionality associated with each tier from the [Zendesk article](https://cobaltio.zendesk.com/hc/en-us/articles/4408839706132-Cobalt-PtaaS-Tiers), I think I need to move the link to our Pricing and Packaging URL (https://www.cobalt.io/pentest-pricing)
If you're interested, I call this text snippet in different doc locations with the `{{% ptaas-tier %}}` variable.
=> [DOCS-122] Update link to pentest tier definitions

content/en/Getting started/Pentest objectives/test-credentials.md, content/en/Getting started/glossary.md
This PR adds several definitions to the [Glossary](https://developer.cobalt.io/getting-started/glossary/).
For a "build" of the change, navigate to https://deploy-preview-119--cobalt-docs.netlify.app/getting-started/glossary/#cobalt-users . (While glossaries are normally set up in alphabetical order, I think it makes sense to group these types of Cobalt users together -- until I have a separate page that describes functionality for each user type, which is _probably_ beyond the scope of a Getting Started Guide. IOW, this PR is an MVC.) 
Based on the permissions, I've also added a definition for SAML, build here: https://deploy-preview-119--cobalt-docs.netlify.app/getting-started/glossary/#security-assertion-markup-language
FYI, I'm also using these definitions to help define UI copy for …
=> [DOCS-123] Set up defintions for Cobalt org and pentest users

content/en/Getting started/Assets/coverage.md, content/en/Getting started/glossary.md, layouts/shortcodes/min-credits-report.md, layouts/shortcodes/pentest-report-requirements.html
Do not merge until at least late May 31
@yogipetkar This should change everything in our product docs.
Unknown: are we still planning to provide a "Simple" report for 4-7 credits, cc @TheInstaGrahame 
You'll see the proposed changes in the build:
- https://deploy-preview-130--cobalt-docs.netlify.app/getting-started/assets/coverage/
- Each of the (6) methodologies pages below https://deploy-preview-130--cobalt-docs.netlify.app/getting-started/pentest-objectives/methodologies/ 
- https://deploy-preview-130--cobalt-docs.netlify.app/getting-started/checklist/
- https://deploy-preview-130--cobalt-docs.netlify.app/getting-started/glossary/#pentest-report
=> [DOCS-94] Update per new credit definitions

content/en/_index.md
Cobalt API isn't read-only anymore, so this sentence should be updated.
=> NO-TICKET: Remove the read-only statement from docs

.gitignore, content/en/Getting started/glossary.md
I've been pushing for a Single Source of Truth. But that's not always compatible with UI Text, which needs to be "short and sweet". 
To that end, I'm proposing a hybrid solution, where we include UI Text in the main definition, with progressive disclosure that helps the reader who wants to "Learn more.". Here's how the build looks -- and the reader can select the `>` to disclose the full glossary definition.
<added> @molfinn , Courtney, to try the "build" for yourself, navigate to https://deploy-preview-132--cobalt-docs.netlify.app/getting-started/glossary/#organization-owner
Note: this is inspired by how k8s does their glossaries, ref https://kubernetes.io/docs/reference/glossary/
=> [DOCS-144] Set up progressive disclosure for org roles

content/en/BestPractices/style_suggestions.md, content/en/BestPractices/template.md
As discussed during our last [internal] content creators meeting, I've laid out a template and a "style sheet" of sorts. I'd appreciate your review.
I've also "hidden" these markdown files from publishing, so you won't see them. If you want to see a "copy as built", you could review the relevant files in the [`BestPractices/` subdirectory](https://github.com/cobalthq/cobalt-product-public-docs/tree/DOCS-166_guidance_for_pentester_writers/content/en/BestPractices) for the branch.
=> [DOCS-166] Add guidance and a template for pentester writers

styles/cobalt/Substitutions.yml
@ana-dashuk-cobalt 
I think I made a mistake when I suggested that we should always capitalize `asset`. I’ve looked at what competitors do in their literature ([snyk.io](http://snyk.io/), [rapid7.com](http://rapid7.com/), [hackerone.com](http://hackerone.com/)) and they all do not capitalize asset.
=> Revert change to asset in substitutions.yml file

content/en/Getting started/What to Expect/_index.md
@ana-dashuk-cobalt as I go through our plan to convert Zendesk articles, I realized that, for "retesting," we do not include any reference to the PtaaS tier.
=> [NO-TICKET] Update retest description with dependency on PtaaS Tier

content/en/Getting started/What to Expect/_index.md
@mjang 
I need to add Roshan as a reviewer for this PR, but I can't find him on the list of users.
Update: Roshan doesn't have a GitHub account.
The functionality is scheduled for release on August 17. I'm also trying to get a screenshot for a message on the **Pentester Updates** tab from the CX-Collaboration team.
Update: Since they don't have good screenshots without sensitive data, I decided not to include it.
=> [DOCS-168] Pentester Updates

netlify.toml
@mjang-cobalt We are several Hugo versions behind. I'm not sure it's the only file that should be updated, but I only found this one.
https://github.com/gohugoio/hugo/releases
=> [NO-TICKET] Update Hugo version

config.toml
If this eliminates the `_print` pages, as suggested by my online research, this should work.
=> [DOCS-159] Remove option for consolidated page prints

netlify.toml
@ana-dashuk-cobalt I forget why I added `git checkout f82dd5e &&` to the Doscy line in netlify.toml. (IIRC, it was a workaround for something.)
The CI failures in PRs like https://github.com/cobalthq/cobalt-product-public-docs/pull/186 and #187 tell me that line's now a problem.
I hope this PR addresses the problem... (I'll have to rebase against those PRs to be sure.)
=> [DOCS-290] Update docsy theme hash

layouts/partials/section-index.html
Added "manual links" to section names based on the Docsy [shortcode](https://github.com/google/docsy/blob/main/layouts/partials/section-index.html).
`{{ % asset-categories % }}`
That shortcode has the same base name as what you see in the PR, such as …
=> [DOCS-309] Manual Links (Links in Section Names)

config.toml, content/en/search.md, package-lock.json, package.json
@ana-dashuk-cobalt : Let's try this in "production". The "Google Custom Search Engine" configuration is set to developer.cobalt.io, so I don't think this works in Netlify (it does not work locally)
Change: Including a search text box atop the page
`{{ % asset-categories % }}` …
=> [DOCS-76] Implement Google Custom Search Engine

content/en/Platform Deep Dive/Pentests/Pentest Process/Methodologies/_index.md, content/en/Platform Deep Dive/Pentests/Pentest Process/Methodologies/api-methodologies.md, content/en/Platform Deep Dive/Pentests/Pentest Process/Methodologies/cloud.md, content/en/Platform Deep Dive/Pentests/Pentest Process/Methodologies/external-network.md, content/en/Platform Deep Dive/Pentests/Pentest Process/Methodologies/internal-network.md, content/en/Platform Deep Dive/Pentests/Pentest Process/Methodologies/mobile.md, content/en/Platform Deep Dive/Pentests/Pentest Process/Methodologies/web-methodologies.md, content/en/Platform Deep Dive/Pentests/Pentest Process/_index.md, package-lock.json, package.json
- Moved Pentest Methodologies content from Getting Started to Pentest Deep Dive
- Created placeholder _index.md file for Pentest Process
- Included `aliases` to redirect from former location
| Page                                                                                      | Deploy Preview                                                                                                                                   | Comment                                                                                                                                                   |
|-------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------- …
=> [DOCS-207] Move pentest methodologies

content/en/Getting started/glossary.md
@molfinn Added minor updates describing the possibility to switch user roles for Organization Owners.
@mjang FYI
=> [DOCS-222] Org Owners Can Switch User Roles

content/en/BestPractices/_index.md, content/en/search.md, layouts/shortcodes/unstabl3.html, layouts/shortcodes/unstabl3.md
Sprint 2 not yet complete. Including 3 approved articles.
| Best Practices | [[Link]](https://deploy-preview-210--cobalt-docs.netlify.app/bestpractices/) | 3 articles, so far |
`{{ % asset-categories % }}`
https://github.com/cobalthq/cobalt-product-public-docs/tree/main/layo …
=> [DOCS-314] Add sprint 2 pentest contributors

content/en/Getting started/glossary.md, content/en/Integrations/_index.md
Based on internal discussion, noted limit in our integration support to GitHub Cloud
n/a
| [Glossary] | [[Link](https://deploy-preview-217--cobalt-docs.netlify.app/getting-started/glossary/#organization-member)] | [Select "Learn More" to reveal detail] |
| [Integrations] | [[Link](https://deploy-preview-217--cobalt-docs.netlify.app/integrations/)] | [See GitHub in the table] |
`{{ % asset-categories % }}`
You’ve found a …
=> [NO-TICKET] Limit support to GitHub Cloud

content/en/Getting started/what-to-expect.md
| Pentest Expectations | https://deploy-preview-198--cobalt-docs.netlify.app/getting-started/what-to-expect/ | Added info about retests to p. 7 > **Ready for Retest**  |
A new guide about retests will be added as part of the SSoT plan. …
=> [DOCS-190] Free Retesting Duration

content/en/Getting started/Pentest objectives/_index.md, content/en/Getting started/Pentest objectives/pentest-target.md, content/en/Getting started/Pentest objectives/test-credentials.md, content/en/Getting started/Sign In/_index.md, content/en/Getting started/Sign In/account-recovery.md, content/en/Getting started/_index.md, content/en/Getting started/checklist.md, content/en/Getting started/details.md, content/en/Getting started/planning.md, content/en/Getting started/what-to-expect.md, content/en/Platform Deep Dive/Pentests/Pentest Process/Methodologies/_index.md, content/en/Platform Deep Dive/Pentests/Pentest Process/Methodologies/cloud.md, content/en/Platform Deep Dive/Pentests/Pentest Process/Methodologies/internal-network.md, layouts/shortcodes/additional-requirements.html
Several links: changed the format from relative to absolute.
=> [DOCS-317] Update 404 Links

content/en/Integrations/_index.md
| Cobalt Integrations | https://deploy-preview-223--cobalt-docs.netlify.app/integrations/ | `alt` and `title` attributes for images |
That shortcode has the same …
=> [NO_TICKET] Add Alt Text to Images

content/en/Getting started/checklist.md, content/en/Getting started/what-to-expect.md, content/en/PentestStates/_index.md, styles/cobalt/Capitalization.yml, styles/cobalt/Substitutions.yml
| Capitalization.yml | https://github.com/cobalthq/cobalt-product-public-docs/pull/224/files#diff-df9caf1ee0154ef9669eaf5ef47f56354b7b463a81b24fbed4a19eb85fc63514 | Vale rule to check the capitalization of terms specific to Cobalt |
Formatting of pentest states in several articles.
You’ll find the content of the …
=> [DOCS-321] Cobalt Capitalization Rules (Vale)

content/en/Getting started/Assets/_index.md, content/en/Getting started/Pentest objectives/_index.md, content/en/Getting started/Pentest objectives/test-credentials.md, content/en/Getting started/details.md, content/en/Getting started/planning.md, content/en/Getting started/what-to-expect.md, content/en/Integrations/webhooks.md, content/en/Platform Deep Dive/Pentests/Pentest Process/pentest-states.md, content/en/Platform Deep Dive/Pentests/Reports/_index.md, content/en/Platform Deep Dive/Pentests/Reports/customize-report.md, content/en/Platform Deep Dive/Pentests/pentest-types.md
Changed the location of some pages to match our new IA.
Be sure to check for …
=> [NO-TICKET] Move Pages

content/en/Platform Deep Dive/Cobalt Account/_index.md
@mjang-cobalt I decided to name this section "Protect Your Account Data" instead of "Request to Anonymize or Delete Your Account Data" because the section is located on the main Cobalt Account page. It may look discouraging if users see these instructions once they navigate to this section. We may change the location, suggestions are welcome.
| Cobalt Account > Protect Your Personal Data | https://deploy-preview-239--cobalt-docs.netlify.app/platform-deep-dive/cobalt-account/ | |
Help us support a “Write once, publish everywhere” single source of truth. If you see …
=> [DOCS-255] Anonymize or delete your account data

content/en/Getting started/_index.md
| Getting Started > Get in Touch | https://deploy-preview-246--cobalt-docs.netlify.app/getting-started/#get-in-touch | IMO, this content should be on the home page, but it doesn't align with the current content. I suggested a new outline of the home page in a private Slack message. We can move this section later once we change the portal theme. |
I decided to omit the instruction describing how to send a request through the bot on the support portal because:
- The user needs to take more steps to achieve the same result -- comparing to sending an email.
- We're moving content off of Zendesk, so it will make less sense to use the bot to search for answers.
- 4 ways to contact support is too much.
To see how this change looks in …
=> [DOCS-253, -258] Get in Touch

content/en/Platform Deep Dive/Collaboration/Organization/manage-users.md
@mjang-cobalt These changes were earlier updated in https://github.com/cobalthq/cobalt-product-public-docs/pull/220.
| Manage Users > Invite Users | https://deploy-preview-253--cobalt-docs.netlify.app/platform-deep-dive/collaboration/organization/manage-users/#invite-users | New flow for inviting users |
You’ll …
=> [DOCS-278] Invite Multiple Users

content/en/_index.md
| Home page | https://deploy-preview-302--cobalt-docs.netlify.app/ | a11y change: added alt and title attributes to images |
That shortcode has the same base name …
=> [NO-TICKET] Add attributes to images

content/en/Platform Deep Dive/Collaboration/Organization/Organization Settings/saml-sso.md
| Configure SAML SSO | https://deploy-preview-307--cobalt-docs.netlify.app/platform-deep-dive/collaboration/organization/organization-settings/saml-sso/ | Minor update about the certificate | …
=> [NO-TICKET] Troubleshoot SAML SSO Configuration

netlify.toml
Downgrade the Hugo version from 0.110.0 to 0.109.0 to avoid possible problems with the config.toml file.
More info in [Hugo release notes](https://github.com/gohugoio/hugo/releases/tag/v0.110.0).
That shortcode has the same …
=> [DOCS-407] Downgrade Hugo version

content/en/Platform Deep Dive/Assets/_index.md, content/en/Platform Deep Dive/Assets/asset-types.md
| Assets | https://deploy-preview-321--cobalt-docs.netlify.app/platform-deep-dive/assets/ | Added FAQs and updated some details |
That shortcode has the same base …
=> [DOCS-251] Assets Updates

content/en/Platform Deep Dive/Collaboration/Organization/Organization Settings/SAML SSO/_index.md
| SAML SSO | [Link](https://deploy-preview-344--cobalt-docs.netlify.app/platform-deep-dive/collaboration/organization/organization-settings/saml-sso/#enforce-saml-sso) | Added info about SAML enforcement | …
=> [DOCS-440] SAML enforcement

config.toml
| Home page | [Link](https://deploy-preview-345--cobalt-docs.netlify.app/) | Link to Privacy Policy |
That shortcode has the same base name as what you see in the …
=> [NO-TICKET] Change link to Privacy Policy

content/en/Getting started/sign-in.md, content/en/Platform Deep Dive/Cobalt Account/account-recovery.md, content/en/Platform Deep Dive/Cobalt Account/account-settings.md, content/en/Platform Deep Dive/Cobalt Account/password-best-practices.md
| Password Best Practices | [Link](https://deploy-preview-375--cobalt-docs.netlify.app/platform-deep-dive/cobalt-account/password-best-practices/) | |
That …
=> [DOCS-454] Password Best Practices

content/en/Getting started/_index.md, content/en/Platform Deep Dive/Organization/Organization Settings/SAML SSO/okta.md
| Getting Started > Get in Touch | [Link](https://deploy-preview-372--cobalt-docs.netlify.app/getting-started/#get-in-touch) | |
That shortcode has the same base …
=> [NO-TICKET] Minor updates

content/en/Getting started/sign-in.md, content/en/Platform Deep Dive/Cobalt Account/account-recovery.md, layouts/shortcodes/browser-verification-intro.md, layouts/shortcodes/device-verification-intro.md
| Sign In to Cobalt > Browser Verification | [Link](https://deploy-preview-382--cobalt-docs.netlify.app/getting-started/sign-in/#browser-verification) | |
| Troubleshoot Sign-in Issues > We Don’t Recognize Your Browser | [Link](https://deploy-preview-382--cobalt-docs.netlify.app/platform-deep-dive/cobalt-account/account-recovery/#we-dont-recognize-your-browser) | |
You’ve found a …
=> [DOCS-472] Browser verification

content/en/Platform Deep Dive/Organization/Organization Settings/SAML SSO/_index.md, content/en/Platform Deep Dive/Organization/Organization Settings/SAML SSO/okta.md, content/en/Platform Deep Dive/Organization/Organization Settings/SAML SSO/saml-migration.md
| How to Configure SAML 2.0 for Cobalt | [Link](https://deploy-preview-391--cobalt-docs.netlify.app/platform-deep-dive/organization/organization-settings/saml-sso/okta/) |  |
| Configure SAML SSO > Okta | [Link](https://deploy-preview-391--cobalt-docs.netlify.app/platform-deep-dive/organization/organization-settings/saml-sso/#okta) | Intro |
| Update SAML SSO > Okta | [Link](https://deploy-preview-391--cobalt-docs.netlify.app/platform-deep-dive/organization/organization-settings/saml-sso/saml-migration/#okta) | |
Help us support a “Write once, publish everywhere” …
=> [NO-TICKET] Okta gallery app for Cobalt

content/en/Integrations/Jira/jira-server-dc.md
=> [FND-3101] The Jira integration can now be configured for draft pentests

content/en/Integrations/Jira/jira-cloud.md
=> [FND-3101] The Jira Cloud integration can now be configured for draft pentests

content/en/Platform Deep Dive/Organization/Organization Settings/SAML SSO/_index.md, content/en/Platform Deep Dive/Organization/Organization Settings/SAML SSO/saml-migration.md
- Update saml-migration.md
- Update audience domains for SAML to use location subdomain …
=> [FND-3186] Fix SAML config instructions

content/en/Platform Deep Dive/Organization/Organization Settings/SAML SSO/saml-migration.md
=> Remove additional Okta gallery references

content/en/Platform Deep Dive/Organization/Organization Settings/SAML SSO/_index.md
| Configure SAML SSO |  | Fixed docs for Azure AD |
[ ] Did you …
=> [FND-3199] Fix SAML SSO docs for Azure AD

content/en/Platform Deep Dive/Organization/Organization Settings/SAML SSO/_index.md, content/en/Platform Deep Dive/Organization/Organization Settings/SAML SSO/okta.md, content/en/Platform Deep Dive/Organization/Organization Settings/SAML SSO/saml-migration.md
This PR will reintroduce the product docs for SAML Okta Gallery App that we removed as part of the app.cobalt.io --> app.us.cobalt.io URL update.
=> Show Okta Gallery App Instructions within SAML Configs

content/en/Platform Deep Dive/Organization/Organization Settings/SAML SSO/_index.md
| SAML SSO | [Azure AD](https://deploy-preview-431--cobalt-docs.netlify.app/platform-deep-dive/organization/organization-settings/saml-sso/#azure-ad) | Fixed docs for relay state in Azure AD section | …
=> [FND-3210] Fix relay state docs for Azure AD SAML SSO

content/en/Cobalt-API/v2/_index.md
=> Add V2 REST API docs as iframe embed

content/en/Platform Deep Dive/Cobalt Account/account-recovery.md, content/en/Platform Deep Dive/Cobalt Account/account-settings.md
=> [FND-3177] Recovery codes documentation - Fix

content/en/Platform Deep Dive/Cobalt Account/account-recovery.md, content/en/Platform Deep Dive/Cobalt Account/account-settings.md
=> [FND-3307] Embed recovery code videos

content/en/Platform Deep Dive/Scans/_index.md, content/en/Platform Deep Dive/Scans/target_auth.md
https://zombie.atlassian.net/browse/FX-2535
I updated the wording and arrangement from the original Slack post with the help of our AI chat.
| Target auth | https://deploy-preview-470--cobalt-docs.netlify.app/platform-deep-dive/scans/target_auth/ | a new page with all the hacks shared by Probely |
| DAST home |https://deploy-preview-470--cobalt-docs.netlify.app/platform-deep-dive/scans/#how-to-use-the-dast-scanner | Added a link to the new page at the end of the auth section |
Help us support a “Write …
=> [FX-2535] Add a target authentication page

content/en/Platform Deep Dive/Scans/target_auth.md, content/en/Platform Deep Dive/Scans/targets.md
https://deploy-preview-472--cobalt-docs.netlify.app/platform-deep-dive/scans/
Be sure to check for broken links and Alt Text issues. We have a partially automated process,
as described in this section of our repository README:
[Test Links and Alt …
=> [FX-1973] Reorder Scans subpages

layouts/shortcodes/sign-in.md
=> Update shared login URL (sign-in.md)

content/en/Platform Deep Dive/Collaboration/groups.md
Public link to Groups demo video: https://videos.cobalt.io/watch/aLD1nkwYisFLrSXJLdBgAc
[ ] Did you check for broken links and …
=> [FX-3916] Link Groups demo video to Product Documentation

content/en/Platform Deep Dive/Scans/_index.md, content/en/Platform Deep Dive/Scans/target_auth.md, content/en/Platform Deep Dive/Scans/targets.md
Added seed paths and avoided urls
Added a configure target section. 
Removed "Authentication" from the main page and linked to the authentication section in the configure a target section. There is a bit of duplication, but since we'll add the advanced target UI soon, I'd rather do this bigger change later.
You’ve …
=> [FX-3987] Add seed paths and avoided urls docs

content/en/Platform Deep Dive/Collaboration/groups.md
Embedded Groups demo video via Loom into the Groups page
Be sure to check for …
=> [FX-4028] Embed Groups demo video into page

content/en/Platform Deep Dive/Organization/Organization Settings/SAML SSO/_index.md
| SAML SSO | Link | Added information about where to find SAML metadata file |
That shortcode has the same base name as what you see in the PR, such as …
=> [FX-4158] Add information about SAML metadata file

content/en/Integrations/Jira/jira-cloud-migration.md
=> [FX-4085] Document process of switching from legacy Jira to workato Jira - Grayson's tweaks

content/en/Platform Deep Dive/Attack Surface/_index.md
Add ASM IP address information to docs as it is laid out in the product -
```
Scanning originates from IP 35.186.191.105 (US) and 34.89.192.162 (EU).
```
The ports are already listed in the documentation in a section further down in the page.
=> Note IP addresses for outbound ASM requests

content/en/Integrations/_index.md
| Integrations | https://deploy-preview-541--cobalt-docs.netlify.app/integrations/ | Remove native integrations list |
That shortcode has the same base name as …
=> [FX-4787] Remove native integrations list from integrations page

content/en/Integrations/IntegrationBuilder/_index.md, content/en/Platform Deep Dive/Scans/integrations.md
| integration builder | https://deploy-preview-547--cobalt-docs.netlify.app/integrations/integrationbuilder/ ||
| dast integrations | https://deploy-preview-547--cobalt-docs.netlify.app/platform-deep-dive/scans/integrations/ ||
You’ll find the content of the shortcode in the following …
=> [FX-4114] Remove integration builder open beta warnings

content/en/Integrations/IntegrationBuilder/_index.md
- Link 'See authentication best practices' to https://docs.cobalt.io/integrations/integrationbuilder/how-to-guides/#authentication-best-practices that was missing from [here](https://docs.cobalt.io/integrations/integrationbuilder/#connection)
https://github.com/cobalthq/cobalt-product-public-docs/tree/main/la …
=> Add missing link to IB docs

content/en/Integrations/Azure DevOps/_index.md, content/en/Integrations/IntegrationBuilder/_index.md, content/en/Integrations/Jira/_index.md, content/en/Integrations/_index.md, content/en/Integrations/github.md, content/en/Integrations/kenna-security.md
=> SS2-40 updated product docs for engagements integrations

content/en/Integrations/github.md
Document the upcoming deprecation of the legacy GitHub integration. Prefer the Integration Builder over the native GitHub integration feature.
| Integrate GitHub with Cobalt | [Link](https://deploy-preview-560--cobalt-docs.netlify.app/integrations/github/) | Add a warning banner about the upcoming deprecation of the native GitHub integration feature. |
You’ve found a [shortcode](https://gohugo.io/content-management/shortcodes/) …
=> [FX-4864] add deprecation warning to native GitHub integration

content/en/Platform Deep Dive/Organization/Organization Settings/SAML SSO/_index.md
The note advises to leave the domains field blank and enfore SAML turned off until after the connection has been tested and confirmed working.
That shortcode has the same base name as what you see in the PR, such as …
=> [NO-TICKET] Add note about IdP Domains and Enforce SAML fields

content/en/Integrations/IntegrationBuilder/troubleshooting.md
Added "Job has not run to create a ticket for a pentest finding" troubleshooting step here:
https://deploy-preview-568--cobalt-docs.netlify.app/integrations/integrationbuilder/troubleshooting/
That shortcode has the same base …
=> [FX-4976] Explain Integration Builder workaround to re-push a pentest finding

assets/scss/_variables_project.scss, content/en/_index.md, layouts/_default/search.html
1. Updated the Navbar to add a dropshadow.
2. Updated the link styling for active and hover states to remove the bootstrap colors and replace them with our Cobalt blue for active and Navy blue for hover states.
3. Updated navbar links to add !important; to color specification to override global changes made above.
4. Fixed issue with navbar child pages not indenting when active and being flush to the left margin.
5. Added a class for gradient text and added it to style the homepage CTA's for Engagements and DAST.
6. Worked on expanding the 'Search Results' section to be closer to full-width.
- improved but not ideal after removing the 'ml-4' class it was wrapped in.
- still not displaying full width, has something to do with the right sidebar on this page that is now bumped up against the …
=> Styling Updates

.github/workflows/check-branch-name.yml
updating branch name check to allow for numbers in project/ticket
n/a
n/a  …
=> adjust for new jira project names

content/en/Platform Deep Dive/Scans/extra-hosts.md
Ticket: https://zombie.atlassian.net/browse/FX-4910
| Extra hosts | [Link](https://deploy-preview-595--cobalt-docs.netlify.app/platform-deep-dive/scans/extra-hosts/#configuration) | Removed the alert | …
=> [FX-4910] Remove extra host limit note

content/en/Product Updates/_index.md, content/en/Product Updates/release-notes-january-2025.md
- Created a new section for 2025 release notes
- Started the January 2025 release notes page
[ ] Did you check for broken links …
=> Feature/no ticket/january release notes

content/en/Integrations/IntegrationBuilder/How to Guides/jira-cloud-migration.md
- Removed reference to 'Jira Server', as that has been retired by Atlassian
Be …
=> [FX-5255] Update reference to Jira Server to just DC

content/en/Integrations/IntegrationBuilder/_index.md, content/en/Platform Deep Dive/Scans/_index.md, content/en/Platform Deep Dive/Scans/integrations.md, content/en/Product Updates/release-notes-july-2024.md
All videos located below to Loom hosted videos:
- https://docs.cobalt.io/platform-deep-dive/scans/
- https://docs.cobalt.io/platform-deep-dive/scans/integrations/ 
- https://docs.cobalt.io/integrations/integrationbuilder/ 
- https://docs.cobalt.io/product-updates/release-notes-july-2024/  …
=> Update demo videos to Loom

content/en/Product Updates/release-notes-january-2025.md
Added the release note to January 2025 to cover the DAST Blackout Period information for our customers.
[ ] Did you check for …
=> Updating January Release Notes with DAST Blackout Periods

content/en/Platform Deep Dive/Cobalt Account/account-settings.md
| Callout for global MFA enforcement | [Link](https://deploy-preview-626--cobalt-docs.netlify.app/platform-deep-dive/cobalt-account/account-settings/#two-factor-authentication) | This callout will be removed again after the given date | …
=> Add callout for global MFA enforcement

content/en/Integrations/ms-teams.md
=> [CX-263] remove reply action, fix some text

content/en/_index.md
=> Fix homepage redirect to pentest types

content/en/Integrations/ms-teams.md
| MS Teams | [Link](https://deploy-preview-670--cobalt-docs.netlify.app/integrations/ms-teams/) | This is the name we agreed on at the end https://docs.google.com/document/d/1t9p4ww3FfXDs5O_3MPF1ufs_2p-l98On8KdZptFvDCA/edit?tab=t.0 | …
=> Update Cobalt bot name to Cobalt Offensive Security

content/en/Account/account-recovery.md, content/en/Account/sign-in.md, layouts/shortcodes/browser-verification-intro.md
=> Remove docs related to browser verification flow
